print("Data Mahasiswa")
print(20*"=")
nama = input("Masukan Nama anda: ")
print("Nama : ", nama)
nim = int(input("Masukan Nim anda: "))
print("Nim : ", nim)
Jurusan = input("Masukan Jurusan anda: ")
print("Jurusan : ", Jurusan)
alamat = input("Masuan Alamat anda: ")
print("Alamat : ", alamat)

print(20*"=")
print("Hasil cetak data diatas adalah: ")
print("Nim anda adalah : ", nim, " dengan nama : ", nama)
print("Jurusan anda adalah : ", Jurusan, " dengan alamat : ", alamat)
